// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 账户权益概览。
 */
export type AccountOverview = { 
/**
 * 账户总权益（USD）
 */
total_eq_usd: number, iso_eq_usd: number, adj_eq_usd: number, avail_eq_usd: number, upl: number, mgn_ratio: number | null, imr: number | null, mmr: number | null, notional_usd: number | null, 
/**
 * `net_mode` | `long_short_mode`
 */
pos_mode: string, currencies: Array<CurrencyBalance>, fetched_at: number, };

/**
 * 一次账户刷新结果。
 */
export type AccountSnapshot = { overview: AccountOverview, positions: Array<Position>, 
/**
 * 本地留痕的覆盖情况（每次刷新都会顺带写一条，零额外网络请求）
 */
trace: TraceCoverage, 
/**
 * 非致命问题：单个端点失败不会让整次刷新失败
 */
warnings: Array<string>, };

/**
 * 应用与核心版本信息。
 *
 * M0 验收要求「双端可启动并显示版本号」，这个结构体就是那条验收路径的载荷：
 * 它同时证明 IPC 通道可用（前端拿到了它）与迁移已执行（`schema_version` 非 0）。
 */
export type AppInfo = { 
/**
 * 来自 tauri.conf.json —— 版本号的唯一来源（设计文档 §14）
 */
app_version: string, 
/**
 * 来自 Cargo.toml 的 crate 版本，与 app_version 应当一致（有测试守住）
 */
core_version: string, 
/**
 * 读自数据库 `_sqlx_migrations`，不是硬编码常量
 *
 * 显式声明为 number：ts-rs 默认把 i64 映射成 bigint，但 IPC 走 JSON，
 * 前端实际拿到的是 number。两者不一致会让类型声明撒谎（有测试守住这条规则）。
 */
schema_version: number, 
/**
 * `std::env::consts::OS`：linux / windows / android / macos
 */
target_os: string, };

/**
 * 启动时前端需要知道的一切。
 *
 * 合成一个命令而不是让前端串行调用三个，是因为它们的组合决定了「进引导页还是主界面」
 * 这一个决策；分开调用会出现「解锁状态已知、引导标志还没到」的中间态，
 * 界面就会闪一下错误的页面。
 */
export type BootstrapState = { 
/**
 * 密钥库文件是否已存在
 */
vault_exists: boolean, vault_unlocked: boolean, 
/**
 * 首次启动引导是否已完成
 */
onboarding_done: boolean, 
/**
 * 当前标的集（已保存的值，未设置过则是预勾选的默认集）
 */
watchlist: Array<string>, };

/**
 * 凭据元数据（可安全落库、可安全传给前端）。
 */
export type CredentialMeta = { id: string, label: string, 
/**
 * `live` | `demo`
 */
env: string, 
/**
 * 形如 `abcd****ef12`。**明文永不入库。**
 */
api_key_masked: string, 
/**
 * OKX 返回的权限串，如 `read_only,trade`
 */
permissions: string | null, uid_masked: string | null, last_ok_at: number | null, last_error: string | null, created_at: number, };

/**
 * 凭据探测结果（`credentials_test` 的返回）。
 */
export type CredentialProbe = { ok: boolean, permissions: string | null, uid_masked: string | null, 
/**
 * `net_mode` | `long_short_mode`
 */
pos_mode: string | null, 
/**
 * 是否**只读**。为 `false` 时界面必须给出红色警示。
 */
read_only: boolean, error: string | null, };

export type Crowding = "LongCrowded" | "ShortCrowded" | "Balanced";

/**
 * 单币种余额（只保留界面需要的字段）。
 */
export type CurrencyBalance = { ccy: string, eq: number, eq_usd: number, avail_bal: number, cash_bal: number, };

/**
 * 一次实盘刷新结果。
 */
export type LiveSnapshot = { ts: number, 
/**
 * 数据来自缓存（未发起网络请求）
 */
cache_hit: boolean, fetched_at: number, watchlist: Array<string>, instruments: Array<MarketState>, 
/**
 * 非致命问题汇总：单个标的失败不会让整次刷新失败
 */
warnings: Array<string>, };

/**
 * 单标的的完整市场状态。
 */
export type MarketState = { inst_id: string, ts: number, last: number, 
/**
 * 24h 涨跌幅
 */
change_pct: number, high_24h: number, low_24h: number, 
/**
 * USD 成交额（已由基础币成交量 × 价格换算）
 */
volume_24h_usd: number, funding_rate: number, 
/**
 * 资金费率年化（8h 结算 → 日 3 次）
 */
funding_annualized: number, next_funding_rate: number | null, next_funding_time: number | null, open_interest_usd: number | null, basis_pct: number | null, long_short_ratio: number | null, taker_buy_sell_ratio: number | null, ema20: number | null, ema60: number | null, ema200: number | null, rsi14: number | null, atr_pct: number | null, realized_vol: number | null, trend: TrendRegime | null, vol: VolRegime | null, crowding: Crowding, signals: Array<string>, 
/**
 * 拿不到的指标及原因。模板渲染成「数据不可得」，绝不留空。
 */
unavailable: Array<string>, };

/**
 * 标准化后的单个持仓。
 *
 * 刻意保留 `contracts`（张数）与 `size_base`（币数量）两个字段：它们在不同场景下
 * 都有用，且换算过程容易出错——把两者都摆出来，界面和复盘都能一眼看出是否合理。
 */
export type Position = { inst_id: string, pos_id: string, 
/**
 * `long` | `short` | `net`——净持仓模式下恒为 `net`
 */
pos_side: string, 
/**
 * `cross` | `isolated`
 */
mgn_mode: string, lever: number, 
/**
 * 张数（合约）
 */
contracts: number, 
/**
 * 币数量 = 张数 × ctVal × ctMult。换算不到合约信息时为 `None`。
 */
size_base: number | null, avg_px: number, mark_px: number, liq_px: number | null, upl: number, upl_ratio: number, mgn_ratio: number | null, 
/**
 * USD 名义价值，直接取自 OKX 的 `notionalUsd`
 */
notional_usd: number, imr: number | null, mmr: number | null, fee: number, funding_fee: number, realized_pnl: number, created_at: number, updated_at: number, };

export type Regime = { trend: TrendRegime | null, vol: VolRegime | null, 
/**
 * 资金费率必然存在，所以拥挤度总能给出结论
 */
crowding: Crowding, 
/**
 * 规则触发说明。提示词需要「为什么」，不只是「是什么」。
 */
signals: Array<string>, 
/**
 * 无法判定的项及原因。渲染成「数据不可得」，绝不留空。
 */
unavailable: Array<string>, };

/**
 * 留痕覆盖度。随每次刷新一起返回。
 */
export type TraceCoverage = { 
/**
 * 最近 30 天内的留痕条数
 */
records: number, 
/**
 * 是否存在超过阈值的间隙
 */
has_gaps: boolean, 
/**
 * 最长间隙（毫秒），无间隙时为 0
 */
max_gap_ms: number, last_trace_at: number | null, 
/**
 * 直接展示给用户的覆盖度说明
 */
note: string, };

export type TrendRegime = "Uptrend" | "Downtrend" | "Range" | "Transition";

/**
 * 密钥库状态。界面据此决定进入「创建」还是「解锁」。
 */
export type VaultStatus = { 
/**
 * 密钥库文件是否已存在
 */
exists: boolean, unlocked: boolean, };

export type VolRegime = "Low" | "Normal" | "High" | "Extreme";

/**
 * 引导第 3 步的候选标的：按 24h 成交额排序的 Top N 永续合约。
 *
 * 为什么按成交额排：成交额低的合约点差大、数据质量差，而且它们的资金费率与
 * 多空比更容易被单笔大单扭曲——用它们做复盘会得出误导性结论。
 */
export type WatchlistCandidate = { inst_id: string, last: number, 
/**
 * USD 成交额（已由基础币成交量 × 价格换算）
 */
volume_24h_usd: number, 
/**
 * 是否应当默认勾选
 */
preselected: boolean, };
